version: "3.2"
services:
  db:
    container_name: db
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    ports:
      - "5433:5432"
    volumes:
      - pgdata_db:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata_db:
